# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Develop

on:
  push:
    branches: 
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: sudo apt-get install -y graphviz
    - run: npm install
    - run: npm run clean
    - run: npm run lint
    - run: npm run build
    - run: npm run test
    - run: tar -zchf /home/runner/work/jsbattle/jsbattle/jsbattle.tar.gz -C /home/runner/work/jsbattle/jsbattle/packages/ --warning=no-file-changed jsbattle
    - uses: actions/upload-artifact@master
      with:
        name: jsbattle-build
        path: /home/runner/work/jsbattle/jsbattle/jsbattle.tar.gz
